### PR TITLE
feature(loops): Added external loop support

### PR DESCRIPTION
**Pull request by ghost**
```py
from defer import defers

@defers
def f():
    print(1)
    defer: print(3)
    print(2)

for i in range(3):
  f()
```

### CODE REVIEW

**Comment by dankeyy** [comment]
cleared up the except a bit but looks good, thanks for the help man

**Comment by ghost** [comment]
Np. I also modified the code so that it works even when it is inside of statements.

**Comment by dankeyy** [comment]
ye i saw that, gj

**Comment by dankeyy** [comment]
@pneb i think that might have broken some stuff. might have been too quick there. 
i'll revert and investigate further.

**Comment by dankeyy** [comment]
Ok so, upto the loop fix we're good. cherry picked it. (and again good thinking, thanks for that). 
But your statement commit seems to break. 
if you don't mind, go through it again, if all seems good to you, open a different pr for this specific feature and ill review it from there.

**Comment by dankeyy** [comment]
Also about that eval, perhaps we could approach it via locals?

**Comment by ghost** [comment]
Yep, the code is buggy. Fixing it rn

**Comment by ghost** [comment]
Check the new pr

**Pull request merged**
