### PR TITLE
feature(statements support): Added also locals for eval

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by dankeyy** [comment]
This yet doesn't seem to do what you intended.
Test it
(indeed it's better now that you replaced the eval with locals lookup btw, tho I wonder when that might get wrong..)

**Comment by ghost** [comment]
Wdym?

**Comment by ghost** [comment]
Okay, fixing it rn so that it will work on lambda statements

**Comment by dankeyy** [comment]
add some tests while you're at it

**Comment by ghost** [comment]
Done, here's the test code:
```py
from defer import defers

@defers
def test(x):
    defers(lambda: print('first', x))
    defers(lambda: print('second', x))
    defers(lambda: print('third', x))
    return x

for i in range(5):
  print(test(4))
  defer: print(5)
```

Please lmk and send your code here if something bad occurs 🙂

**Comment by dankeyy** [comment]
> Done, here's the test code:
> 
> ```python
> from defer import defers
> 
> @defers
> def test(x):
>     defers(lambda: print('first', x))
>     defers(lambda: print('second', x))
>     defers(lambda: print('third', x))
>     return x
> 
> for i in range(5):
>   print(test(4))
>   defer: print(5)
> ```
> 
> Please lmk and send your code here if something bad occurs slightly_smiling_face

ok so couple of things:
1. you mean `defer` in your code? as in allowing passage by function call (as matches by your function implementation), right?
2.  why do you think this approach is necessary? are there any other needs for this specialization? 
I personally want to stick with this syntax for as much as possible (as this was the point of the repo to begin with).
4. i've created https://github.com/dankeyy/defer.py/pull/5/ as a way to acccept lambda, is there something im not considering that makes it not good enough?

**Comment by dankeyy** [comment]
btw for future questionings i'll probably add a couple more node types, if you don't see one that makes sense to have support to, i probably just haven't got around to it, unless it's something weird like an assert node.

**Pull request closed without merging**
